import PrincipalSFundo from './principal sem fundo.png'
import Favicon from './favicon.png'
import WhppIcon from './whatsapp.png'
import InstaIcon from './instagram.png'
import SpotifyIcon from './spotify.png'
import LogoWhite from './logo-White.png'
import LogoCompleta from './Logo_Complete.png'
import Coding from './coding.png'
import Gear from './gear.png'
import PlaceHolder2 from './placeholder-two.png'
import Arrow from './Arrow.png'
import Foto1 from './foto1.jpg'
import Foto2 from './foto2.jpg'
import Foto3 from './foto3.jpg'
import Foto4 from './foto4.jpg'
import Foto5 from './foto5.jpg'
import Foto6 from './foto6.jpg'
import Foto7 from './foto7.jpg'
import Foto8 from './foto8.jpg'
import Foto9 from './foto9.jpg'
import Foto10 from './foto10.jpg'
import Foto11 from './foto11.jpg'
import Foto12 from './foto12.jpg'
import Foto13 from './foto13.jpg'
import Foto14 from './foto14.jpg'
import Foto15 from './foto15.jpg'
import ArrowWhite from './leftArrow.png'
export default PrincipalSFundo;
export { ArrowWhite, Favicon, WhppIcon, InstaIcon, SpotifyIcon, LogoWhite, LogoCompleta, Coding, Gear, PlaceHolder2, Arrow, Foto1, Foto2, Foto3, Foto4, Foto5, Foto6, Foto7, Foto8, Foto9, Foto10, Foto11, Foto12, Foto13, Foto14, Foto15, }